### PR TITLE
Fix  + Clearer handling of unexpected nulls

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Clearer handling of unexpected nulls

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
I have a problem with `Executor.currentExecutor()` returning `null` both when the job runs on the master and when the jobs runs on a "Dumb Agent".

I am not familiar with  `Executor.currentExecutor()`, I am not clear with the cause.

```
Started by user anonymous
[Pipeline] node
Running on vagrant in /home/vagrant/jenkins-home/workspace/my-maven-pipeline-with-settings
[Pipeline] {
[Pipeline] withMaven
Using Maven Installation default
Using maven exec: /home/vagrant/jenkins-home/tools/hudson.tasks.Maven_MavenInstallation/default/bin/mvn
[Pipeline] // withMaven
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Executor.currentExecutor() is NULL, probably not desired
Finished: FAILURE
```

```
node ('vagrant'){
    withMaven(mavenSettingsConfig: 'my-maven-settings', maven: 'default') {
       sh "env"
       sh "mvn --version"
    }
}
```

**Comment by imod** [comment]
@cyrille-leclerc yeah, as you see from my comment in the https://github.com/jenkinsci/pipeline-maven-plugin/pull/10 I also noticed it does not work. But same as you, I have no idea how to fix it. I was hopping jesse could have a look at it, but hi did not react on my @ mention :(

**Comment by cyrille-leclerc** [comment]
@imod I can ping Jesse next week if it helps. This week is thanksgiving in the US.

**Comment by imod** [comment]
that would be great, thanks!

**Comment by jglick** [comment]
Huh?! There is already a `build` field, just use it.

**Comment by imod** [comment]
@jglick oh man - I must have been blind!!! many thanks!!!

**Comment by cyrille-leclerc** [comment]
@imod I have applied @jglick's fix. Tested successfully executing pipelines on "master" and on an external ssh build agent.

**Comment by imod** [comment]
@cyrille-leclerc there is an other location at https://github.com/cyrille-leclerc/pipeline-maven-plugin/blob/8f5c8b794a4e5ea689740a099b83464ddbd9d042/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution.java#L575

**Comment by cyrille-leclerc** [comment]
@imod "maven global settings file" fixed and tested successfully.

Test:

```groovy
node ('vagrant'){
    withMaven(
            mavenSettingsConfig: 'my-maven-settings', 
            globalMavenSettingsConfig: 'my-global-maven-settings', 
            maven: 'default') {
       sh "env"
       sh "mvn --version"
       sh 'cat $MVN_SETTINGS'
       sh 'cat $GLOBAL_MVN_SETTINGS'
    }
}
```

**Comment by imod** [comment]
@cyrille-leclerc btw. many thanks!

**Comment by cyrille-leclerc** [comment]
@imod you're welcome!

**Pull request merged**
